# This workflow has been replaced by build-and-release.yml
# Please use the new workflow for building and releasing

name: Legacy Release (Deprecated)

on:
  workflow_dispatch:

jobs:
  deprecated:
    name: Deprecated Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Show deprecation notice
        run: |
          echo "⚠️ This workflow is deprecated"
          echo "Please use the 'Build and Release' workflow instead"
          echo "File: .github/workflows/build-and-release.yml"
